### ISSUE TITLE
Error at importing git repo

### ISSUE THREAD

**Issue by labgeek03** [Stvad/CrowdAnki#130]
Hi there,
I have a problem with the feature "_CrowdAnki: Import from git repository_". 
If I want to import my git repo I will get this error message.

![Screenshot 2021-04-29 114816](https://user-images.githubusercontent.com/81388165/116532803-f6b30480-a8e0-11eb-811e-f17f4e737735.jpg)

My repo is here: [https://github.com/labgeek03/Active-Recall-Framework.git](url)
I turned off every other extension that I use, but the error is still there.

I hope someone knows a fix for that issue.

Greetings
the labgeek03

**Comment by aplaice** [comment]
This likely doesn't help with the issue you're encountering (i.e. it's a separate issue), but looking at your `deck.json`, you've been bitten by #106/#116 — due to a bug in CrowdAnki, the `deck_config_uuid`s of all the child decks are wrong. It's straightforward to change — just replace all occurrences of `ad65e290-59da-11eb-ad13-448a5b8ef3a7` with `aace692f-59da-11eb-a2f2-448a5b8ef3a7`.

<hr/>

Regarding the error in the screenshot it seems to be a Windows permission error; perhaps try removing the relevant git directory (`AppData\Roaming\Anki2\addons21\XXXX\user_files\WHS\Active-Recall-Framework\`)?

**Comment by labgeek03** [comment]
Thanks for the quick response.
I did both of your recommendations and it works now.
Thanks a lot!
