### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by wildthyme** [Stvad/CrowdAnki#140]
it’s been a year since the last release. i’d like to use the non-github git import functionality that seems to exist in master, but it isn’t in the released version. is there anything blocking releasing an update? or could i have instructions for producing a working package myself? (i want to use a private git server to distribute decks to a group of people but can’t go expecting them to set up a development version of the add-on)

**Comment by aplaice** [comment]
The non-github git import functionality is in the latest release (it was added in 0.8) and in the version from AnkiWeb.  Most of the changes in master since 0.9 have been to keep up with changes to Anki itself (e.g. 0.9 doesn't work with some of the later versions of Anki, while the `master` and the AnkiWeb versions do) and to fix some bugs.

Once the currently open bug-fix PRs have been merged (which should happen soon — I mainly need to test that they all still work together with the very latest Anki), we could have a 0.9.1 release, on GitHub, and probably soon after on AnkiWeb!

You could build a working package with `pipenv install; ./package_plugin.sh` (you don't need `pyuic5` since the UI files haven't changed), but ideally please wait for the bug fixes from the PRs!

**Comment by wildthyme** [comment]
realized i was only running the outdated anki 2.1.15 [from nixpkgs](https://github.com/NixOS/nixpkgs/issues/78449) and that this was why it pulled an old version of the add-on. my mistake. the README text on ankiweb does need to be updated as it still describes the github version, though. thank you!
