### ISSUE TITLE
"maximum recursion depth exceeded" error when I try to export to JSON

### ISSUE THREAD

**Issue by matrixmayhem** [Stvad/CrowdAnki#172]
When I try to export a deck I am getting a "maximum recursion depth exceeded" error. 
I am on 
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 5.15.2 PyQt 5.15.5.

**Comment by aplaice** [comment]
I'm sorry to hear that and thanks for reporting!

I'm unable to reproduce the error on my system (also with 2.1.54 Qt5), so slightly more info would be valuable.

What OS are you using? Could you attach the full backtrace (sanitised of any personal info (likely only the username in the paths, if it's private))? Does the error happen with every deck or just a specific one?

**Comment by ijgnd** [comment]
@matrixmayhem : I get a similar error in CrowdAnki but only if I have the add-on [Enhanced Cloze (for Anki 2.1)](https://ankiweb.net/shared/info/1990296174) enabled. Could you disable the add-on "Enhanced Cloze", restart Anki and try again. 

If the error disappears you have the same problem as me which seems to be caused by "Enhanced Cloze". Then just wait. An update should be coming soon. Or monitor the discussion in #179. 

&nbsp;

If you still get the error without "Enhanced Cloze" it's a different problem. Maybe another add-on conflict among the over 1000 add-ons. Just do the steps from https://faqs.ankiweb.net/when-problems-occur.html:

> If the problem goes away when add-ons are disabled, you can narrow down the culprit by disabling one or more add-ons, restarting Anki, and seeing if the problem goes away. If you have lots of them, you can select the top half of your add-ons in the Add-ons screen and disable them. If after restarting Anki, the problem is still there, try the other half instead. Once you’ve found the half that is causing the problem, divide that half into half again, and repeat. You should be able to narrow it down in around ~6 steps that way. 

Then post the full error message and also from the main windows Help->About. In the window that opens click the "Copy Debug Info" and paste the output here.

**Comment by matrixmayhem** [comment]
> @matrixmayhem : I get a similar error in CrowdAnki but only if I have the add-on [Enhanced Cloze (for Anki 2.1)](https://ankiweb.net/shared/info/1990296174) enabled. Could you disable the add-on "Enhanced Cloze", restart Anki and try again.
> 
> If the error disappears you have the same problem as me which seems to be caused by "Enhanced Cloze". Then just wait. An update should be coming soon. Or monitor the discussion in #179.
> 
>  
> 
> If you still get the error without "Enhanced Cloze" it's a different problem. Maybe another add-on conflict among the over 1000 add-ons. Just do the steps from https://faqs.ankiweb.net/when-problems-occur.html:
> 
> > If the problem goes away when add-ons are disabled, you can narrow down the culprit by disabling one or more add-ons, restarting Anki, and seeing if the problem goes away. If you have lots of them, you can select the top half of your add-ons in the Add-ons screen and disable them. If after restarting Anki, the problem is still there, try the other half instead. Once you’ve found the half that is causing the problem, divide that half into half again, and repeat. You should be able to narrow it down in around ~6 steps that way.
> 
> Then post the full error message and also from the main windows Help->About. In the window that opens click the "Copy Debug Info" and paste the output here.

You're right. Enhanced Cloze was responsible. With the new update of Enhanced Cloze, the problem went away. thanks.
