### ISSUE TITLE
Importing .json doesn't create cards in children decks, only in the parent deck

### ISSUE THREAD

**Issue by dayjaby** [Stvad/CrowdAnki#7]
I have the following deck hierarchy:

Kumo (Parent deck)
- 001.txt
- 002.txt
- ...

All those .txt decks contain several notes. However, after importing, only "Kumo" contains cards.

To reproduce this error: Import [this JSON file](https://github.com/dayjaby/Kumo/blob/master/Yomichan::kumo/Yomichan::kumo.json).

Desired behaviour: Each of those .txt decks shall contain cards.

**Comment by Stvad** [comment]
I've fixed some hierarchy problems (not directly related to this one, but may influence). 
But the main issue here is that in the deck, you've submitted - there is a ton of UUID collisions on Notes, I'm not sure what has caused this, but this is ultimately the reason why all cards end up in Kumo (because there is a collision for each note in *.txt subdecks)

**Comment by Stvad** [comment]
Ah, I see, It's caused by the fact that you have cards of one note in different deck and the Note on export is duplicated
