### ISSUE TITLE
Re-importing a deck forces already-existing cards to be moved

### ISSUE THREAD

**Issue by dayjaby** [Stvad/CrowdAnki#8]
How to reproduce:
1. Import a .json deck.
2. Move some of the imported cards into another Anki deck
3. Re-import the same .json deck, which reverts step 2

Desired behaviour: Don't move already existing cards

There might be a more fundamental problem with this issue: If CrowdAnki is used by several people, then it's not possible for them to have different deck hierarchies. Once upon a time I programmed a similar (yet incomplete) collaboration plugin and I solved this problem by not exporting single decks, but rather entire note types and their notes. The advantage of this approach is that every individual person can have individual deck hierarchies. Would this correspond to your idea of how syncing/collaborating is supposed to work?

**Comment by Stvad** [comment]
Hi, thank you for testing the plugin. Regarding this particular one, though - it's mentioned in the tutorial as current expected behaviour. I will explain my reasons and answer your question at length later this week, as I'm now travelling.

**Comment by Stvad** [comment]
Different aspects of this one mentioned here: https://github.com/Stvad/CrowdAnki/issues/7

**Comment by Stvad** [comment]
So regarding reason for this behavior and my current thoughts regarding your second question:
Notes can be moved within the hierarchy. In my understanding card is an integral subpart of a Note and so should be moved on update when Note is moved (I can't discriminate by card because I don't store information about cards. And I don't do that because as far as I can tell all information besides statistics and the thing we're talking about is generated).
Having cards from one note in separate decks makes a little sense for me. At least on my current level of understanding, but from the fact that you're reporting this I may assume, that you use this functionality.

As you've discovered, judging by your commit in a fork of the plugin - this behavior can be easily changed and I may consider making it optional in the future (you're welcome to contribute btw :)).

Another thing to consider may be to store correspondence of Note field and the deck UUID. And then on import react correspondingly. But I don't like this option because it will make editing of JSON file outside of Anki complicated and we don't want' this for collaboration reasons.

My concept of the collaboration focuses on a deck or a deck hierarchy. Note model is the note configuration and not related to the structural organization in my vision.

Yes getting an update could be annoying in some cases if you altered Deck hierarchy after importing things. But given how I think about collaboration workflow right now it should not be a problem you will encounter often (i.e. during active collaboration phase you want to maintain same hierarchy anyway. And after this phase, you can customize it in a way that you don't want to contribute|not acceptable to contribute for some reasons. After that, if you haven't updated hierarchy - merge should be seamless. If you did, well, it will involve more work).

**Comment by Stvad** [comment]
further tracked in #23
